@startuml

class ParkingBoy << Entity >> {
  List<ParkingLot> parkingLots

  + ParkingLot getParkingLot()
  + void setParkingLots (List<ParkingLot> parkingLots)
  + List<ParkingLot> getParkingLots()
}

class ParkingLot << Entity >> {
  int capacity
  Map <Ticket, Car> parkedCars

  + Ticket park(Car car)
  + Car take(Ticket ticket)
  + boolean available()
}

Class Car << Value Object >> {
    PlateNumber plateNumber
}

Class Ticket << Value Object >> {
}

Ticket "1" *--> "1" Car
ParkingLot "1" o--> "0..many" Ticket
ParkingBoy "1" o--> "0..many" ParkingLot

@enduml
